spring:
  application:
    name: system_inventory
  cloud:
    config:
      enabled: false
  docker:
    compose:
      enabled: false
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/system_inventory
    username: ${DB_USERNAME:alekzander}
    password: ${DB_PASSWORD:MRFabri2002@@}
logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.data.mongodb: DEBUG
server:
  port: 4141